fastify/github-action-merge-dependabot

README.md, action.yml, index.js
=> feat: allow excluding packages

package.json, src/index.js
Stops `npm install` from throwing warnings
=> chore(package): add repository, bugs, and homepage values

README.md
Documents how to use approve-only with GitHub's automerge and explain the limitation that prevents workflow runs from being triggered on the commits done by this action if used with the built-in GitHub token.
Also explain the limitation using the provided github token and the lack of support for dependabot preview.
Closes #11.
=> docs: document how to use approve-only with GitHub's automerge

README.md, dist/index.js, src/index.js
In order to clarify that github app installation is mandatory
- added warning on 400 response
- updated README.md
=> add install github app warning

package-lock.json, package.json
Reverts fastify/github-action-merge-dependabot#73
Reverts #73 
Now that #72 has been merged it should no happen again
=> Revert "chore(deps): bump node-fetch from 2.6.1 to 3.0.0"

README.md
adding credits to NearForm: its staff has committed the 99% of this GHA 😄
=> sponsored by NearForm

dist/index.js, src/action.js, test/action.test.js
Fixes:
https://github.com/nearform/get-jwks/runs/4507965746?check_suite_focus=true
```
Invalid version: 3
```
=> fix invalid version error

.github/workflows/notify-release.yml
=> chore: add notify-release workflow

.github/workflows/ci.yml
=> chore: use semver major version of actions

.github/workflows/release.yml
=> chore: gha major tag

.github/workflows/ci.yml
=> chore: run ci on prs and pushes to main branch only

.github/workflows/release.yml, dist/index.js, package-lock.json
=> fix: regenerate build output and package-lock.json

.eslintrc, dist/index.js, package-lock.json, package.json, src/action.js, src/getTargetInput.js, src/github-client.js, src/log.js, src/moduleVersionChanges.js, src/util.js, test/action.test.js, test/github-client.test.js, test/log.test.js, test/moduleChanges.js, test/moduleVersionChanges.test.js, test/util.test.js
**No functional changes are done in this PR**
This PR contains only formatting changes done automatically by eslint after setting up the eslint-prettier integration, which was missing and causing lots of formatting inconsistencies.
Fixes #225
=> chore: formatting

README.md, dist/index.js, src/util.js
Resolves https://github.com/fastify/workflows/issues/58
=> change parseCommaSeparatedValue to parseCommaOrSemicolonSeparatedValue

.github/workflows/notify-release.yml
As per new instructions in from the action
=> chore: add published release trigger to notify release workflow

README.md, action.yml
=> feat: add GHES support with skip-commit-verification

test/log.test.js
=> fix: remove deprecation warning

.github/workflows/check-linked-issues.yml, .github/workflows/notify-release.yml, .github/workflows/release.yml
=> chore: use nearform-actions

package-lock.json, package.json
=> chore: remove gitdiff-parser as dependency

test/action.test.js
fix: #539 added testcase for auto merge
=> fix: #539 added testcase for auto merge
