.github/dependabot.yml, .github/workflows/ci.yml, .prettierrc, README.md, action.yml, src/index.js, src/util.js
Because of https://github.com/fastify/github-action-merge-dependabot/issues/8, we need a different way to run builds when dependabot PRs are merged.
GitHub now has an automerge option in the repository settings, which allows merging a PR when requirements are satisfied. Those requirements usually include:
- a green build
- one approval
This feature allows this action to only provide the approval without merging, so that we can use the built-in GH feature to do the merge and run the CI checks instead.
It's clearly not exactly the same thing, because using GH's automerge would automerge other PRs besides the dependabot ones, but it's good enough.
Closes #8
=> feat: approve only

README.md, action.yml, dist/index.js
Switches the backing API url to the fastify-owned one in GCP
=> chore: gcp api url

.github/workflows/ci.yml, .gitignore, .prettierrc, .taprc, README.md, action.yml, dist/index.js, package-lock.json, package.json, src/checkTargetMatchToPR.js, src/getTargetInput.js, src/index.js, src/util.js, test/checkTargetMatchToPR.test.js, test/getTargetInput.test.js
=> feat: add target parameter, make it major by default

README.md, dist/index.js, src/getTargetInput.js, src/index.js, test/getTargetInput.test.js
The target value can be one of the `major, premajor, minor, preminor, patch, prepatch or prerelease`. This PR adds another value `any` which can be used to run the action without any semver version checks.
Documentation has been updated
Closes #95
=> "any" value added to target option

README.md, action.yml
The default value for `target` was still `major` but it has been changed to `any` here https://github.com/fastify/github-action-merge-dependabot/pull/99. 
Docs has been fixed as well, however I'm not sure about adding new tests... it would be great to have tests in place to prevent bugs like this in the future _i.e._ ensure that the documented defaults are correct.
Thanks!
_This is my first PR here so sorry in advance if anything is missing! 🙏_
=> fix: default value for target on action.yml

README.md, dist/index.js, src/checkTargetMatchToPR.js, test/action.test.js, test/checkTargetMatchToPR.test.js
fixes https://github.com/fastify/github-action-merge-dependabot/issues/124
It should support submodules as well (the #98 PR adds the `any` option to skip this check)
=> fix: semver like titles

README.md
as titled, moving the migration guide to the readme from:
https://github.com/fastify/github-action-merge-dependabot/releases/tag/v3.0.1
=> chore: add migration guide

.github/workflows/release.yml
=> feat: add release action

dist/index.js, src/moduleVersionChanges.js, test/action.test.js, test/moduleChanges.js
Avoid returning false (which as far as I can see was not being used in any case) and always return an object.
Closes #172 
=> fix: Standardize getModuleVersionChanges return type

.taprc, dist/index.js, src/action.js, src/util.js, test/action.test.js, test/github-client.test.js, test/log.test.js, test/moduleChanges.js, test/moduleVersionChanges.test.js, test/util.test.js
Add missing tests to achieve 100% test coverage and enforce it so tests fail if coverage drop from 100%.
Some of the tests will probably never happen in a real world scenario but are required for full coverage nonetheless.
Closes #177.
=> Add missing tests

dist/index.js, src/action.js, src/util.js, test/action.test.js, test/util.test.js
Improve handling of invalid PR titles.
Parse package name from branch name to avoid issues.
Closes #185
=> fix: improve PR Title parsing, handle invalid inputs

dist/index.js, package.json, src/action.js, src/moduleVersionChanges.js, src/util.js, test/action.test.js, test/moduleChanges.js, test/moduleVersionChanges.test.js, test/util.test.js
This change re-add support for commit hash versions on both PR diff and title (which I believe were removed after the PR diff changes). They will be merged independently of the target option since the hash doesn't have that information.
Closes #199 
Closes https://github.com/nearform/github-action-notify-release/pull/189
=> Handle commit hash versions

README.md
=> chore: mention app uninstallation when migrating

.github/workflows/release.yml
Updates release workflow to provide a dropdown to select semver to bump
=> feat: use dropdown for semver selection in release workflow

.github/workflows/check-linked-issues.yml, .github/workflows/ci.yml, .github/workflows/notify-release.yml, .github/workflows/release.yml, README.md, action.yml
=> Pass the default github token to the github-token input

README.md, action.yml, dist/index.js, src/action.js, src/github-client.js, src/util.js, test/action.test.js, test/github-client.test.js
Close https://github.com/fastify/github-action-merge-dependabot/issues/301.
=> Add an option to use github's auto merge

action.yml
Suppress #310
Fixes #311 
In the issue, it believes the problem is cause by running the action in `pull` event and the filter to restrict on `main` branch will solve the problem.
However, the main cause is `dependabot/fetch-metadata` never expected to run on [`push` event](https://github.com/dependabot/fetch-metadata/blob/ec8c26ab81e2df3417db090db57bc7aefd7f114b/src/dependabot/verified_commits.ts#L12) and the branch other than [`dependabot/*`](https://github.com/dependabot/fetch-metadata/blob/ec8c26ab81e2df3417db090db57bc7aefd7f114b/src/dependabot/update_metadata.ts#L35) . So, it will [throws on certain edge case](https://github.com/dependabot/fetch-metadata/blob/main/src/main.ts#L33-L46).
This PR restrict `dependabot/fetch-metadata` only runs on the event that should run.
and the [Code …
=> fix: dependabot/fetch-metadata throw on push event

README.md, dist/index.js, src/action.js, src/util.js, test/action.test.js, test/util.test.js
Fixes #363
We got little further with the initial GHES support, but it still hits with the verifySignatures:
```
Warning: PR contains invalid dependabot commit signatures, skipping.
```
=> Fix GHES support

action.yml
Accidental miss with #411  as parameters need to be accessed using `inputs`
This work is part of issue #378
=> fix: typo in action.yml

dist/index.js, src/action.js, test/action.test.js
This stops the action from failing when target is not match, just log a message instead. 
Resolves #423.
=> feat: stop failing action when bump is higher than target and log info instead

README.md, dist/index.js, src/action.js, src/util.js, test/action.test.js
This PR adds an output variable `merge_status` containing the merge status so users can run other actions based on the result of the merge.
Closes #323
=> feat: add output with merge status

dist/index.js, src/action.js, src/mapUpdateType.js, src/util.js, test/action.test.js
This PR is a fix suggestion.
fix #452 
=> fix(priority): invert semver matching to avoid unfound semver

.taprc, package.json
=> chore: use .taprc and show coverage report

package.json, test/util.test.js
Removes the first warning, which is part of the unit tests
=> fix: suppress warning in ci/cd pipeline, add lint:fix script

README.md, action.yml, dist/index.js, src/action.js, src/util.js, test/action.test.js
Fixes #443. 
Sample configuration, copied from `Readme`:
```yml
steps:
- uses: fastify/github-action-merge-dependabot@v3
with:
target-development: 'major'
target-production: 'minor'
```
=> feat: specify separate targets for dev and production

README.md, action.yml, dist/index.js, src/action.js, src/util.js, test/action.test.js
Fixes #539. Basically there were issues:
- output was never proxied to the consuming workflow
- we introduced a new status for auto-merge, a case not covered before
=> fix: merge status output not working
